output-format: text

strictness: high

autodetect: false

ignore-paths:
  - docs
  - jenkins
  - API
  - config-template.py

pylint:
  options:
    good-names:
      - e
      - i
      - k
      - df
      - v
    max-line-length: 200

pep8:
  disable:
    - E303
  full: true
  options:
    max-line-length: 200

pyroma:
  run: true

mccabe:
  options:
    max-complexity: 20
