output-format: grouped

strictness: veryhigh
doc-warnings: true
test-warnings: false

max-line-length: 120

autodetect: false

ignore-patterns:
  - ^setup.py$

ignore-paths:
  - docs
  - jenkins
  - etc

pylint:
  disable:
    - star-args
    - missing-docstring
    - too-many-arguments
    - invalid-name
    - too-few-public-methods
    - too-many-branches

  enable:
    - fixme

  options:
    max-line-length: 120

pep8:
    run: true
    full: true
    disable:
        - E302
        - E305
        - E501

pep257:
  run: false
  disable:
      - D202
      - D203

dodgy:
    run: true

pyroma:
  run: false

pyflakes:
    run: true

mccabe:
  options:
    max-complexity: 20
