output-format: text

strictness: high

autodetect: false

ignore-paths:
  - docs
  - jenkins
  - API
  - config-template.py

pylint:
  disable:
    - import-error
    - too-many-branches

  options:
    good-names:
      - i
      - k
      - v
      - df
    max-line-length: 120

pep8:
  disable:
    - E303
    - L237
  full: true
  options:
    max-line-length: 120

pyroma:
  run: true

mccabe:
  options:
    max-complexity: 20
