output-format: grouped

strictness: high
doc-warnings: true
test-warnings: false
max-line-length: 120

autodetect: false

ignore-paths:
  - docs/
  - jenkins/
  - etc/

pylint:
  disable:
    - bad-builtin
    - too-few-public-methods
    - missing-docstring
    - star-args

  options:
    good-names:
      - i
      - k
      - v
      - df
    max-line-length: 120

pep8:
  disable:
    - E126

  full: true
  options:
    max-line-length: 120

pep257:
  disable:
    - D100
    - D101
    - D102
    - D103
    - D104
    - D205
    - D400
    - D401

pyroma:
  run: true

mccabe:
  options:
    max-complexity: 20
