# SEODeploy Config File

seotesting_name: SEODeploy
log_file: seodeploy.log
samples_filename: path_samples.txt

# Sampling #TODO: Pull out to CLI
confidence_level: 95.0
confidence_interval: 5.0
url_limit: 1000
max_threads: 1

modules_activated:

  headless:
    batch_size: 5
    pyppeteer_chromium_revision: 769582
    network_preset: Regular3G
    prod_host: https://locomotive.agency
    stage_host: https://staging-locomotiveagency.kinsta.cloud
    stage_auth_user: user
    stage_auth_pass: pass

    user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36

    replace_staging_host: True

    ignore:
      content:
          canonical: False
          robots: False
          title: False
          meta_description: False
          h1: False
          h2: False
          links: True
          images: True
          schema: False

      performance:
          nodes: True
          resources: 0.50
          layout_duration: True
          recalc_style_duration: True
          script_duration: True
          v8_compile_duration: True
          task_duration: True
          task_other_duration: True
          thread_time: True
          jd_heap_used_size: True
          js_heap_total_size: True
          time_to_first_byte: True
          first_paint: True
          first_contentful_paint: 0.50
          largest_contentful_paint: True
          time_to_interactive: 0.50
          dom_content_loaded: True
          dom_complete: True
          cumulative_layout_shift: 0.50

      coverage:
        summary:
          total_unused: True
          total_bytes: True
          unused_pc: 0.50

        css:
          total_unused: True
          total_bytes: True
          unused_pc: 0.50

        js:
          total_unused: True
          total_bytes: True
          unused_pc: 0.50


  contentking:
    cms_api_key: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    report_api_key: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    endpoint: https://api.contentkingapp.com/v1/

    api_timeout: 20
    per_page: 300
    timezone: Europe/Amsterdam
    batch_size: 10
    batch_wait: 10
    time_col: unstable_last_checked_at

    prod_host: https://locomotive.agency
    prod_site_id: 7-453638
    stage_host: https://staging-locomotiveagency.kinsta.cloud
    stage_site_id: 4-17924878

    replace_staging_host: True

    ignore:

      issues:
          analytics/analytics_missing: False
          analytics/visual_analytics_missing: True
          h1/duplicate: False
          h1/incorrect_length: False
          h1/missing: False
          h1/too_many: False
          canonical_link/incorrectly_canonicalized: False
          canonical_link/missing: False
          canonical_link/points_to_unindexable: False
          canonical_link/too_many: False
          images/alt_attribute: False
          images/title_attribute: False
          links/broken: False
          links/redirected: True
          links/to_canonicalized: True
          meta_description/duplicate: False
          meta_description/incorrect_length: False
          meta_description/missing: False
          meta_description/too_many: False
          title/duplicate: False
          title/incorrect_length: False
          title/missing: False
          title/too_many: False
          open_graph/description_incorrect_length: False
          open_graph/description_missing: False
          open_graph/image_missing: False
          open_graph/title_incorrect_length: False
          open_graph/title_missing: False
          open_graph/url_missing: False
          twitter_cards/description_incorrect_length: False
          twitter_cards/description_missing: False
          twitter_cards/image_missing: False
          twitter_cards/site_missing: False
          twitter_cards/title_incorrect_length: False
          twitter_cards/title_missing: False
          twitter_cards/type_invalid: False
          twitter_cards/type_missing: False
          xml_sitemap/incorrectly_missing: True
          xml_sitemap/incorrectly_present: True

      content:
          canonical: False
          title: False
          meta_description: False
          h1: False
          h2: False
          meta_robots: False
          open_graph_description: False
          open_graph_image: False
          open_graph_title: False
          open_graph_type: False
          open_graph_url: False
          twitter_card: False
          twitter_site: False
          google_analytics: False

      schema: False

modules_inactive:
