# SEO Testing Config File

seotesting_name: SEOTesting
log_file: seotesting.log
samples_filename: path_samples.txt

# Sampling #TODO: Pull out to CLI
confidence_level: 95.0
confidence_interval: 5.0
url_limit: 1000
max_threads: 5

modules_activated:
  headless:
    batch_size: 10
    prod_host: https://locomotive.agency
    stage_host: https://locomotive.agency
    user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
    ignore_content:
        canonical: False
        title: False
        meta_description: False
        h1: False
        h2: False


  contentking:
    cms_api_key: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    report_api_key: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    endpoint: https://api.contentkingapp.com/v1/

    api_timeout: 20
    per_page: 300
    timezone: Europe/Amsterdam
    batch_size: 10
    batch_wait: 10
    time_col: unstable_last_checked_at

    prod_host: https://locomotive.agency
    prod_site_id: 7-453638
    stage_host: https://locomotive.agency
    stage_site_id: 7-453638

    ignore_issues:
        analytics/analytics_missing: False
        analytics/visual_analytics_missing: False
        h1/duplicate: False
        h1/incorrect_length: False
        h1/missing: False
        h1/too_many: False
        canonical_link/incorrectly_canonicalized: False
        canonical_link/missing: False
        canonical_link/points_to_unindexable: False
        canonical_link/too_many: False
        images/alt_attribute: False
        images/title_attribute: False
        links/broken: False
        links/redirected: False
        links/to_canonicalized: False
        meta_description/duplicate: False
        meta_description/incorrect_length: False
        meta_description/missing: False
        meta_description/too_many: False
        title/duplicate: False
        title/incorrect_length: False
        title/missing: False
        title/too_many: False
        open_graph/description_incorrect_length: False
        open_graph/description_missing: False
        open_graph/image_missing: False
        open_graph/title_incorrect_length: False
        open_graph/title_missing: False
        open_graph/url_missing: False
        twitter_cards/description_incorrect_length: False
        twitter_cards/description_missing: False
        twitter_cards/image_missing: False
        twitter_cards/site_missing: False
        twitter_cards/title_incorrect_length: False
        twitter_cards/title_missing: False
        twitter_cards/type_invalid: False
        twitter_cards/type_missing: False
        xml_sitemap/incorrectly_missing: False
        xml_sitemap/incorrectly_present: False

    ignore_content:
        canonical: False
        title: False
        meta_description: False
        h1: False
        h2: False
        meta_robots: False
        open_graph_description: False
        open_graph_image: False
        open_graph_title: False
        open_graph_type: False
        open_graph_url: False
        twitter_card: False
        twitter_site: False
        google_analytics: False
